/** Official titles. Generated from the supplied list. Do not invent names. */

export interface CatalogTitle {
	title: string;
	/** Kept visible on the right when the row truncates. */
	suffix?: string;
	/** Search only. Never shown in a suggester row. */
	aliases?: readonly string[];
}

export const PUBLICATION_ENTRIES: readonly CatalogTitle[] = [
	{ title: "\"Can We Enjoy Life Forever?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"How Can You Have a Happy Family?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"Who Is the True God?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"Is Anyone Listening to Our Prayers?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"Does Jesus’ Advice Work Today?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"How Will God’s Kingdom Solve Our Problems?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"Is Living Without Pain or Sadness Possible?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"Will You Ever See Your Loved Ones Who Have Died?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"Do All Religions Please God?\" Tiny Tract", suffix: "Tiny Tract" },
	{ title: "\"Invitation to Congregation Meetings\"", aliases: ["Meeting Invite"] },
	{ title: "\"What Is the Kingdom of God?\" Tract", suffix: "Tract" },
	{ title: "\"Where Can We Find Answers to Life’s Big Questions?\" Tract", suffix: "Tract" },
	{ title: "\"How Do You View the Bible?\" Tract", suffix: "Tract" },
	{ title: "\"How Do You View the Future?\" Tract", suffix: "Tract" },
	{ title: "\"What Is the Key to Happy Family Life?\" Tract", suffix: "Tract" },
	{ title: "\"Who Really Controls the World?\" Tract", suffix: "Tract" },
	{ title: "\"Will Suffering Ever End?\" Tract", suffix: "Tract" },
	{ title: "\"Can the Dead Really Live Again?\" Tract", suffix: "Tract" },
	{ title: "\"Enjoy Life Forever!—Introductory Bible Lessons\" Brochure", suffix: "Brochure", aliases: ["\"Enjoy Life Forever\" Brochure"] },
	{ title: "\"Return to Jehovah\" Brochure", suffix: "Brochure" },
	{ title: "\"Who Are Doing Jehovah’s Will Today?\" Brochure", suffix: "Brochure" },
	{ title: "\"My Bible Lessons Kid’s\" Brochure", suffix: "Brochure" },
	{ title: "\"How Can You Have a Happy Life?\" Brochure", suffix: "Brochure" },
	{ title: "\"Good News From God!\" Brochure", suffix: "Brochure" },
	{ title: "\"Listen to God\" Brochure", suffix: "Brochure" },
	{ title: "\"Listen to God and Live Forever\" Brochure", suffix: "Brochure" },
	{ title: "\"The Pathway to Peace and Happiness\" Brochure", suffix: "Brochure" },
	{ title: "\"Real Faith—Your Key to a Happy Life\" Brochure", suffix: "Brochure" },
	{ title: "\"Was Life Created?\" Brochure", suffix: "Brochure" },
	{ title: "\"The Origin of Life—Five Questions Worth Asking\" Brochure", suffix: "Brochure" },
	{ title: "\"What You Can Do About Loneliness\" Awake!", suffix: "Awake!" },
	{ title: "\"Coping With Rising Prices\" Awake!", suffix: "Awake!" },
	{ title: "\"What Has Happened to Respect?\" Awake!", suffix: "Awake!" },
	{ title: "\"Can Our Planet Survive?—Reasons for Hope\" Awake!", suffix: "Awake!" },
	{ title: "\"Is World Peace Possible?\" Watchtower", suffix: "Watchtower" },
	{ title: "\"An End to War—How?\" Watchtower", suffix: "Watchtower" },
	{ title: "\"Right and Wrong—A Guide You Can Trust\" Watchtower", suffix: "Watchtower" },
	{ title: "\"Mental Health—Help From the Bible\" Watchtower", suffix: "Watchtower" },
	{ title: "\"Breaking the Cycle of Hatred\" Watchtower", suffix: "Watchtower" },
	{ title: "\"A Secure Future—How Can You Find It?\" Watchtower", suffix: "Watchtower" },
	{ title: "\"A Better World Is Near\" Watchtower", suffix: "Watchtower" },
	{ title: "\"Why Pray?\" Watchtower", suffix: "Watchtower" },
	{ title: "\"Lasting Blessings From a Loving God\" Watchtower", suffix: "Watchtower" },
	{ title: "\"What Is God’s Kingdom?\" Watchtower", suffix: "Watchtower" },
	{ title: "\"The Search for Truth\" Watchtower", suffix: "Watchtower" },
	{ title: "\"Is This Life All There Is?\" Watchtower", suffix: "Watchtower" },
	{ title: "\"A World in Turmoil—How You Can Cope\" Awake!", suffix: "Awake!" },
	{ title: "\"Should You Believe in a Creator?—You Decide\" Awake!", suffix: "Awake!" },
	{ title: "\"Technology—Your Master or Your Servant?\" Awake!", suffix: "Awake!" },
	{ title: "\"Wisdom for Life and Happiness\" Awake!", suffix: "Awake!" },
	{ title: "\"Is There a Cure for Prejudice?\" Awake!", suffix: "Awake!" },
	{ title: "\"5 Questions About Suffering Answered\" Awake!", suffix: "Awake!" },
	{ title: "\"Find Relief From Stress\" Awake!", suffix: "Awake!" },
	{ title: "\"Can the Bible Make Your Life Better?\" Awake!", suffix: "Awake!" },
	{ title: "\"Enjoy Life Forever!—An Interactive Bible Course\" Book", suffix: "Book" },
	{ title: "\"Lessons You Can Learn From the Bible\" Book", suffix: "Book" },
	{ title: "\"Jesus—The Way, the Truth, the Life\" Book", suffix: "Book" },
];

export const MEDIA_ENTRIES: readonly CatalogTitle[] = [
	{ title: "\"What Happens at Our Conventions?\"" },
	{ title: "\"The Good News According to Jesus—Video Series Trailer\"" },
	{ title: "\"You Are Invited: 2026 “Eternal Happiness” Convention of Jehovah’s Witnesses\"" },
	{ title: "\"Feature Bible Drama Preview: The Good News According to Jesus: Episodes 4, 5, and 6\"" },
	{ title: "\"Remember Jesus' Death\"" },
	{ title: "\"Why Study the Bible?\"" },
	{ title: "\"Why Study the Bible?—Full Length\"" },
	{ title: "\"What Happens at a Bible Study?\"" },
	{ title: "\"What Happens at a Kingdom Hall?\"" },
	{ title: "\"Jehovah’s Witnesses—Who Are We?\"" },
	{ title: "\"Welcome to Your Bible Study\"" },
	{ title: "\"Comfort for Those Who Mourn\"" },
	{ title: "\"Is There Hope for the Dead?\"" },
	{ title: "\"Your Family Can Be Happy Introduction\"" },
	{ title: "\"Would You Like Good News?\"" },
	{ title: "\"Was Life Created? Introduction\"" },
	{ title: "\"Who Is the True God?\"" },
	{ title: "\"How Can You Have a Happy Family?\"" },
	{ title: "\"Is Living Without Pain or Sadness Possible?\"" },
	{ title: "\"Was the Universe Created?\"" },
	{ title: "\"Is God Real?\"" },
	{ title: "\"Does God Have a Name?\"" },
	{ title: "\"Is Friendship With God Possible?\"" },
	{ title: "\"Who Is the Author of the Bible?\"" },
	{ title: "\"How Can We Be Sure the Bible Is True?\"" },
	{ title: "\"How to Read the Bible\"" },
	{ title: "\"Why Did God Create the Earth?\"" },
	{ title: "\"What Is the Purpose of Life?\"" },
	{ title: "\"Where Can You Find Answers to Life’s Big Questions?\"" },
	{ title: "\"What Is the Condition of the Dead?\"" },
	{ title: "\"Is Hell a Real Place of Torment?\"" },
	{ title: "\"Is Jesus Christ God?\"" },
	{ title: "\"Why Did Jesus Die?\"" },
	{ title: "\"What Is God’s Kingdom?\"" },
	{ title: "\"God’s Kingdom Began Ruling in 1914\"" },
	{ title: "\"The World Has Changed Since 1914\"" },
	{ title: "\"Are Natural Disasters Acts of God?\"" },
	{ title: "\"Why Does God Allow Suffering?\"" },
	{ title: "\"Why Do You Believe What You Believe?\"" },
	{ title: "\"Does God Accept All Forms of Worship?\"" },
	{ title: "\"Must You Belong to an Organized Religion to Worship God?\"" },
	{ title: "\"Does God Listen to All Prayers?\"" },
	{ title: "\"Does God Approve the Use of Images in Worship?\"" },
	{ title: "\"What Is God’s View of Marriage?\"" },
	{ title: "\"What Is the Origin of Christmas?\"" },
	{ title: "\"Is Pornography a Sin Against God?\"" },
	{ title: "\"Learn From Jehovah’s Friends—Ruth\"" },
	{ title: "\"Learn From Jehovah’s Friends—Elijah\"" },
	{ title: "\"Jehovah Is a Real Person\"" },
	{ title: "\"Learn From Jehovah’s Friends—Mephibosheth\"" },
	{ title: "\"Become Jehovah’s Friend Preview: Jehovah Is a Real Person\"" },
	{ title: "\"Learn From Jehovah’s Friends—Joseph\"" },
	{ title: "\"Be Hospitable\"" },
	{ title: "\"Learn From Jehovah’s Friends—Joshua and Caleb\"" },
	{ title: "\"You Could Pioneer!\"" },
	{ title: "\"Learn From Jehovah’s Friends—Abigail\"" },
	{ title: "\"The Greatest Act of Love\"" },
	{ title: "\"Learn From Jehovah’s Friends—Deborah\"" },
	{ title: "\"Learn From Jehovah’s Friends—Abel\"" },
	{ title: "\"God Makes It Grow\"" },
	{ title: "\"Learn From Jehovah’s Friends—Jeremiah\"" },
	{ title: "\"Jehovah Is Our Father\"" },
	{ title: "\"Learn From Jehovah’s Friends—Hananiah, Mishael, and Azariah\"" },
	{ title: "\"You Are Precious to Jehovah\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"You Are Precious to Jehovah\" Caleb and Sofia Video"] },
	{ title: "\"The Steps to Baptism\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"The Steps to Baptism\" Caleb and Sofia Video"] },
	{ title: "\"Become an Unbaptized Publisher\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Become an Unbaptized Publisher\" Caleb and Sofia Video"] },
	{ title: "\"Who Should Be My Friend?\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Who Should Be My Friend?\" Caleb and Sofia Video"] },
	{ title: "\"Why Obey God if We Can’t See Him?\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Why Obey God if We Can’t See Him?\" Caleb and Sofia Video"] },
	{ title: "\"Don't Give Up\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Don't Give Up\" Caleb and Sofia Video"] },
	{ title: "\"Does Jehovah Answer Prayers?\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Does Jehovah Answer Prayers?\" Caleb and Sofia Video"] },
	{ title: "\"Should We Celebrate Birthdays?\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Should We Celebrate Birthdays?\" Caleb and Sofia Video"] },
	{ title: "\"Jehovah Forgives\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Jehovah Forgives\" Caleb and Sofia Video"] },
	{ title: "\"Love Your Neighbor\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Love Your Neighbor\" Caleb and Sofia Video"] },
	{ title: "\"Making Sacrifices\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Making Sacrifices\" Caleb and Sofia Video"] },
	{ title: "\"Discipline Is Love\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Discipline Is Love\" Caleb and Sofia Video"] },
	{ title: "\"The Best Use of Time\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"The Best Use of Time\" Caleb and Sofia Video"] },
	{ title: "\"Help Others\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Help Others\" Caleb and Sofia Video"] },
	{ title: "\"Be Good in the Ministry\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Be Good in the Ministry\" Caleb and Sofia Video"] },
	{ title: "\"Make Jehovah Happy\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Make Jehovah Happy\" Caleb and Sofia Video"] },
	{ title: "\"Love Jehovah’s House\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Love Jehovah’s House\" Caleb and Sofia Video"] },
	{ title: "\"Enduring Loss\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Enduring Loss\" Caleb and Sofia Video"] },
	{ title: "\"Be Humble\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Be Humble\" Caleb and Sofia Video"] },
	{ title: "\"Endure Despite Unjust Treatment\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Endure Despite Unjust Treatment\" Caleb and Sofia Video"] },
	{ title: "\"See Yourself in Paradise\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"See Yourself in Paradise\" Caleb and Sofia Video"] },
	{ title: "\"The Ransom\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"The Ransom\" Caleb and Sofia Video"] },
	{ title: "\"Making Friends\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Making Friends\" Caleb and Sofia Video"] },
	{ title: "\"Jehovah's Name\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Jehovah's Name\" Caleb and Sofia Video"] },
	{ title: "\"Jehovah Designed All Things\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Jehovah Designed All Things\" Caleb and Sofia Video"] },
	{ title: "\"One Man, One Woman\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"One Man, One Woman\" Caleb and Sofia Video"] },
	{ title: "\"You Can Be Patient!\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"You Can Be Patient!\" Caleb and Sofia Video"] },
	{ title: "\"Be Appreciative\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Be Appreciative\" Caleb and Sofia Video"] },
	{ title: "\"Be Generous\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Be Generous\" Caleb and Sofia Video"] },
	{ title: "\"Be Truthful\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Be Truthful\" Caleb and Sofia Video"] },
	{ title: "\"Respect Jehovah's House\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Respect Jehovah's House\" Caleb and Sofia Video"] },
	{ title: "\"Protect Your Children\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Protect Your Children\" Caleb and Sofia Video"] },
	{ title: "\"Pay Attention at the Meetings\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Pay Attention at the Meetings\" Caleb and Sofia Video"] },
	{ title: "\"Prepare Your Comment\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Prepare Your Comment\" Caleb and Sofia Video"] },
	{ title: "\"Jehovah Will Help You Be Bold\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Jehovah Will Help You Be Bold\" Caleb and Sofia Video"] },
	{ title: "\"Caleb and Sophia Visit Bethel\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Caleb and Sophia Visit Bethel\" Caleb and Sofia Video"] },
	{ title: "\"An Animated Series That Touches Little Hearts\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"An Animated Series That Touches Little Hearts\" Caleb and Sofia Video"] },
	{ title: "\"Forgive Freely\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Forgive Freely\" Caleb and Sofia Video"] },
	{ title: "\"Be Kind and Share\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Be Kind and Share\" Caleb and Sofia Video"] },
	{ title: "\"“Jehovah . . . Created All Things”\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"“Jehovah . . . Created All Things”\" Caleb and Sofia Video"] },
	{ title: "\"Be Neat and Clean\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Be Neat and Clean\" Caleb and Sofia Video"] },
	{ title: "\"Giving Makes You Happy\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Giving Makes You Happy\" Caleb and Sofia Video"] },
	{ title: "\"Please and Thank You\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Please and Thank You\" Caleb and Sofia Video"] },
	{ title: "\"Let's Go in Service\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Let's Go in Service\" Caleb and Sofia Video"] },
	{ title: "\"Stealing Is Bad\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Stealing Is Bad\" Caleb and Sofia Video"] },
	{ title: "\"Pray Anytime\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Pray Anytime\" Caleb and Sofia Video"] },
	{ title: "\"Obey Jehovah\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Obey Jehovah\" Caleb and Sofia Video"] },
	{ title: "\"Obey Your Parents\" Become Jehovah’s Friend", suffix: "Become Jehovah’s Friend", aliases: ["\"Obey Your Parents\" Caleb and Sofia Video"] },
	{ title: "\"When a Loved One Dies\"" },
	{ title: "\"Take Delight in God’s Promises of Peace\"" },
	{ title: "\"Take Delight in God’s Promises of Peace—Excerpt\"" },
	{ title: "\"“Jehovah Will Treat His Loyal One in a Special Way”\"" },
	{ title: "\"Lessons From the Book of Job—Animal Creation\"" },
	{ title: "\"Lessons From the Book of Job—Natural Forces\"" },
	{ title: "\"As the Storm Approaches, Maintain Your Focus on Jesus!—Future Kingdom Blessings\"" },
	{ title: "\"Follow Jesus' Pattern—Keep On Asking, Seeking, and Knocking!\"" },
	{ title: "\"Appreciating the Benefits of Kingdom Rule\"" },
	{ title: "\"The Resurrection—Soon a Reality\"" },
	{ title: "\"A Tool to Help Us Explain Our Beliefs About 1914\"" },
	{ title: "\"Imitate Women of Strong Faith!—Martha\"" },
];

export const LESSON_ENTRIES: readonly { title: string; review: boolean; reviewSection?: 1 | 2 | 3 | 4 }[] = [
	{ title: "01 How Can the Bible Help You?", review: false },
	{ title: "02 The Bible Gives Hope", review: false },
	{ title: "03 Can You Trust the Bible?", review: false },
	{ title: "04 Who Is God?", review: false },
	{ title: "05 The Bible Is God’s Message to Us", review: false },
	{ title: "06 How Did Life Begin?", review: false },
	{ title: "07 What Is Jehovah Like?", review: false },
	{ title: "08 You Can Be Jehovah’s Friend", review: false },
	{ title: "09 Draw Close to God Through Prayer", review: false },
	{ title: "10 How Can the Meetings of Jehovah’s Witnesses Benefit You?", review: false },
	{ title: "11 How You Can Get the Most Out of the Bible", review: false },
	{ title: "12 What Will Help You to Keep Studying the Bible?", review: false },
	{ title: "Section 1 Review", review: true, reviewSection: 1 },
	{ title: "13 How False Religion Misrepresents God", review: false },
	{ title: "14 How Can Our Worship Be Pleasing to God?", review: false },
	{ title: "15 Who Is Jesus?", review: false },
	{ title: "16 What Did Jesus Do While on Earth?", review: false },
	{ title: "17 What Is Jesus Like?", review: false },
	{ title: "18 How to Identify Real Christians", review: false },
	{ title: "19 Are Jehovah’s Witnesses Real Christians?", review: false },
	{ title: "20 How the Congregation Is Organized", review: false },
	{ title: "21 How Is the Good News Being Preached?", review: false },
	{ title: "22 How Can You Share the Good News?", review: false },
	{ title: "23 Baptism—A Worthwhile Goal!", review: false },
	{ title: "24 What Is the Truth About Angels?", review: false },
	{ title: "25 What Is God’s Purpose for Us?", review: false },
	{ title: "26 Why Do Evil and Suffering Exist?", review: false },
	{ title: "27 How Can Jesus’ Death Save Us?", review: false },
	{ title: "28 Show Appreciation for What Jehovah and Jesus Did for You", review: false },
	{ title: "29 What Happens When We Die?", review: false },
	{ title: "30 Your Loved Ones Can Live Again!", review: false },
	{ title: "31 What Is God’s Kingdom?", review: false },
	{ title: "32 God’s Kingdom Now Rules!", review: false },
	{ title: "33 What the Kingdom Will Accomplish", review: false },
	{ title: "Section 2 Review", review: true, reviewSection: 2 },
	{ title: "34 How Can We Show Our Love for Jehovah?", review: false },
	{ title: "35 How to Make Good Decisions", review: false },
	{ title: "36 Be Honest in All Things", review: false },
	{ title: "37 What the Bible Says About Work and Money", review: false },
	{ title: "38 Appreciate the Gift of Life", review: false },
	{ title: "39 God’s View of Blood", review: false },
	{ title: "40 How Can We Be Clean in God’s Eyes?", review: false },
	{ title: "41 What Does the Bible Say About Sex?", review: false },
	{ title: "42 What Does the Bible Say About Singleness and Marriage?", review: false },
	{ title: "43 How Should Christians View Alcohol?", review: false },
	{ title: "44 Do All Celebrations Please God?", review: false },
	{ title: "45 What It Means to Be Neutral", review: false },
	{ title: "46 Why Make a Dedication and Get Baptized?", review: false },
	{ title: "47 Are You Ready to Get Baptized?", review: false },
	{ title: "Section 3 Review", review: true, reviewSection: 3 },
	{ title: "48 Choose Your Friends Wisely", review: false },
	{ title: "49 How Can Your Family Be Happy?—Part 1", review: false },
	{ title: "50 How Can Your Family Be Happy?—Part 2", review: false },
	{ title: "51 How Can You Please Jehovah With Your Speech?", review: false },
	{ title: "52 Why Our Clothing and Appearance Matter", review: false },
	{ title: "53 Choose Entertainment That Pleases Jehovah", review: false },
	{ title: "54 The Role of “the Faithful and Discreet Slave”", review: false },
	{ title: "55 Support Your Local Congregation", review: false },
	{ title: "56 Maintain Unity in the Congregation", review: false },
	{ title: "57 What if You Commit a Serious Sin?", review: false },
	{ title: "58 Remain Loyal to Jehovah", review: false },
	{ title: "59 You Can Endure Persecution", review: false },
	{ title: "60 Continue Making Progress", review: false },
	{ title: "Section 4 Review", review: true, reviewSection: 4 },
];
